const express = require("express");
const router = express.Router();

const elementosTabla = [
    {index: 0, Symbol: "H", Group: "OtrosNoMetales" },
    {index: 1, Symbol: "", Group: "Vacio" },
    {index: 2, Symbol: "", Group: "Vacio" },
    {index: 3, Symbol: "", Group: "Vacio"},
    {index: 4, Symbol: "", Group: "Vacio" },
    {index: 5, Symbol: "", Group: "Vacio" },
    {index: 6, Symbol: "", Group: "Vacio" },
    {index: 7, Symbol: "", Group: "Vacio"},
    {index: 8, Symbol: "", Group: "Vacio" },
    {index: 9, Symbol: "", Group: "Vacio"},
    {index: 10, Symbol: "", Group: "Vacio" },
    {index: 11, Symbol: "", Group: "Vacio" },
    {index: 12, Symbol: "", Group: "Vacio" },
    {index: 13, Symbol: "", Group: "Vacio" },
    {index: 14, Symbol: "", Group: "Vacio" },
    {index: 15, Symbol: "", Group: "Vacio" },
    {index: 16, Symbol: "", Group: "Vacio" },
    {index: 17, Symbol: "He", Group: "GasesNobles"},

    {index: 18, Symbol: "Li", Group: "Alcalinos"},
    {index: 19, Symbol: "Be", Group: "Alcalinotérreos"},
    {index: 20, Symbol: "", Group: "Vacio" },
    {index: 21, Symbol: "", Group: "Vacio" },
    {index: 22, Symbol: "", Group: "Vacio" },
    {index: 23, Symbol: "", Group: "Vacio"},
    {index: 24, Symbol: "", Group: "Vacio" },
    {index: 25, Symbol: "", Group: "Vacio" },
    {index: 26, Symbol: "", Group: "Vacio" },
    {index: 27, Symbol: "", Group: "Vacio"},
    {index: 28, Symbol: "", Group: "Vacio" },
    {index: 29, Symbol: "", Group: "Vacio"},
    {index: 30, Symbol: "B", Group: "Metaloides" },
    {index: 31, Symbol: "C", Group: "OtrosNoMetales" },
    {index: 32, Symbol: "N", Group: "OtrosNoMetales" },
    {index: 33, Symbol: "O", Group: "OtrosNoMetales" },
    {index: 34, Symbol: "F", Group: "Halogenos" },
    {index: 35, Symbol: "Ne", Group: "GasesNobles"},
    
    {index: 36, Symbol: "Na", Group: "Alcalinos" },
    {index: 37, Symbol: "Mg", Group: "Alcalinotérreos" },
    {index: 38, Symbol: "", Group: "Vacio" },
    {index: 39, Symbol: "", Group: "Vacio"},
    {index: 40, Symbol: "", Group: "Vacio" },
    {index: 41, Symbol: "", Group: "Vacio" },
    {index: 42, Symbol: "", Group: "Vacio" },
    {index: 43, Symbol: "", Group: "Vacio"},
    {index: 44, Symbol: "", Group: "Vacio" },
    {index: 45, Symbol: "", Group: "Vacio"},
    {index: 46, Symbol: "", Group: "Vacio" },
    {index: 47, Symbol: "", Group: "Vacio" },
    {index: 48, Symbol: "Al", Group: "OtrosMetales" },
    {index: 49, Symbol: "Si", Group: "Metaloides" },
    {index: 50, Symbol: "P", Group: "OtrosNoMetales" },
    {index: 51, Symbol: "S", Group: "OtrosNoMetales" },
    {index: 52, Symbol: "Cl", Group: "Halogenos" },
    {index: 53, Symbol: "Ar", Group: "GasesNobles"},

    {index: 54, Symbol: "K", Group: "Alcalinos"},
    {index: 55, Symbol: "Be", Group: "Alcalinotérreos"},
    {index: 56, Symbol: "Sc", Group: "Metales-de-transicion" },
    {index: 57, Symbol: "Ti", Group: "Metales-de-transicion" },
    {index: 58, Symbol: "V", Group: "Metales-de-transicion" },
    {index: 59, Symbol: "Cr", Group: "Metales-de-transicion"},
    {index: 60, Symbol: "Mn", Group: "Metales-de-transicion" },
    {index: 61, Symbol: "Fe", Group: "Metales-de-transicion" },
    {index: 62, Symbol: "Co", Group: "Metales-de-transicion" },
    {index: 63, Symbol: "Ni", Group: "Metales-de-transicion"},
    {index: 64, Symbol: "Cu", Group: "Metales-de-transicion" },
    {index: 65, Symbol: "Zn", Group: "Metales-de-transicion"},
    {index: 66, Symbol: "Ga", Group: "OtrosMetales" },
    {index: 67, Symbol: "Ge", Group: "Metaloides" },
    {index: 68, Symbol: "As", Group: "Metaloides" },
    {index: 69, Symbol: "Se", Group: "OtrosNoMetales" },
    {index: 70, Symbol: "Br", Group: "Halogenos" },
    {index: 71, Symbol: "Kr", Group: "GasesNobles"},

    {index: 72, Symbol: "Rb", Group: "Alcalinos"},
    {index: 73, Symbol: "Sr", Group: "Alcalinotérreos"},
    {index: 74, Symbol: "Y", Group: "Metales-de-transicion" },
    {index: 75, Symbol: "Zr", Group: "Metales-de-transicion" },
    {index: 76, Symbol: "Nb", Group: "Metales-de-transicion" },
    {index: 77, Symbol: "Mo", Group: "Metales-de-transicion"},
    {index: 78, Symbol: "Tc", Group: "Metales-de-transicion" },
    {index: 79, Symbol: "Ru", Group: "Metales-de-transicion" },
    {index: 80, Symbol: "Rh", Group: "Metales-de-transicion" },
    {index: 81, Symbol: "Pd", Group: "Metales-de-transicion"},
    {index: 82, Symbol: "Ag", Group: "Metales-de-transicion" },
    {index: 83, Symbol: "Cd", Group: "Metales-de-transicion"},
    {index: 84, Symbol: "In", Group: "OtrosMetales" },
    {index: 85, Symbol: "Sn", Group: "OtrosMetales" },
    {index: 86, Symbol: "Sb", Group: "Metaloides" },
    {index: 87, Symbol: "Te", Group: "Metaloides" },
    {index: 88, Symbol: "I", Group: "Halogenos" },
    {index: 89, Symbol: "Xe", Group: "GasesNobles"},

    {index: 90, Symbol: "Cs", Group: "Alcalinos"},
    {index: 91, Symbol: "Ba", Group: "Alcalinotérreos"},
    {index: 92, Symbol: "La-Lu", Group: "Metales-de-transicion" },
    {index: 93, Symbol: "Hf", Group: "Metales-de-transicion" },
    {index: 94, Symbol: "Ta", Group: "Metales-de-transicion" },
    {index: 95, Symbol: "W", Group: "Metales-de-transicion"},
    {index: 96, Symbol: "Re", Group: "Metales-de-transicion" },
    {index: 97, Symbol: "Os", Group: "Metales-de-transicion" },
    {index: 98, Symbol: "Ir", Group: "Metales-de-transicion" },
    {index: 99, Symbol: "Pt", Group: "Metales-de-transicion"},
    {index: 100, Symbol: "Au", Group: "Metales-de-transicion" },
    {index: 101, Symbol: "Hg", Group: "Metales-de-transicion"},
    {index: 102, Symbol: "Tl", Group: "OtrosMetales" },
    {index: 103, Symbol: "Pb", Group: "OtrosMetales" },
    {index: 104, Symbol: "Bi", Group: "OtrosMetales" },
    {index: 105, Symbol: "Po", Group: "Metaloides" },
    {index: 106, Symbol: "At", Group: "Halogenos" },
    {index: 107, Symbol: "Rn", Group: "GasesNobles"},

    {index: 108, Symbol: "Fr", Group: "Alcalinos"},
    {index: 109, Symbol: "Ra", Group: "Alcalinotérreos"},
    {index: 110, Symbol: "Ac-Lr", Group: "Metales-de-transicion" },
    {index: 111, Symbol: "Rf", Group: "Metales-de-transicion" },
    {index: 112, Symbol: "Db", Group: "Metales-de-transicion" },
    {index: 113, Symbol: "Sg", Group: "Metales-de-transicion"},
    {index: 114, Symbol: "Bh", Group: "Metales-de-transicion" },
    {index: 115, Symbol: "Hs", Group: "Metales-de-transicion" },
    {index: 116, Symbol: "Mt", Group: "Metales-de-transicion" },
    {index: 117, Symbol: "Ds", Group: "Metales-de-transicion"},
    {index: 118, Symbol: "Rg", Group: "Metales-de-transicion" },
    {index: 119, Symbol: "Cn", Group: "Metales-de-transicion"},
    {index: 120, Symbol: "Nh", Group: "OtrosMetales" },
    {index: 121, Symbol: "Fl", Group: "OtrosMetales" },
    {index: 122, Symbol: "Mc", Group: "OtrosMetales" },
    {index: 123, Symbol: "Lv", Group: "OtrosMetales" },
    {index: 124, Symbol: "Ts", Group: "Halogenos" },
    {index: 125, Symbol: "Og", Group: "GasesNobles"},

    {index: 126, Symbol: "", Group: "Vacio" },
    {index: 127, Symbol: "", Group: "Vacio" },
    {index: 128, Symbol: "", Group: "Vacio"},
    {index: 129, Symbol: "", Group: "Vacio" },
    {index: 130, Symbol: "", Group: "Vacio" },
    {index: 131, Symbol: "", Group: "Vacio" },
    {index: 132, Symbol: "", Group: "Vacio"},
    {index: 133, Symbol: "", Group: "Vacio" },
    {index: 134, Symbol: "", Group: "Vacio"},
    {index: 135, Symbol: "", Group: "Vacio" },
    {index: 136, Symbol: "", Group: "Vacio" },
    {index: 137, Symbol: "", Group: "Vacio" },
    {index: 138, Symbol: "", Group: "Vacio" },
    {index: 139, Symbol: "", Group: "Vacio" },
    {index: 140, Symbol: "", Group: "Vacio" },
    {index: 141, Symbol: "", Group: "Vacio" },
    {index: 142, Symbol: "", Group: "Vacio" },
    {index: 143, Symbol: "", Group: "Vacio" },

    {index: 144, Symbol: "", Group: "Vacio" },
    {index: 145, Symbol: "", Group: "Vacio" },
    {index: 146, Symbol: "", Group: "Vacio"},
    {index: 147, Symbol: "La", Group: "Lantanidos" },
    {index: 148, Symbol: "Ce", Group: "Lantanidos" },
    {index: 149, Symbol: "Pr", Group: "Lantanidos" },
    {index: 150, Symbol: "Nd", Group: "Lantanidos"},
    {index: 151, Symbol: "Pm", Group: "Lantanidos" },
    {index: 152, Symbol: "Sm", Group: "Lantanidos"},
    {index: 153, Symbol: "Eu", Group: "Lantanidos" },
    {index: 154, Symbol: "Gd", Group: "Lantanidos" },
    {index: 155, Symbol: "Tb", Group: "Lantanidos" },
    {index: 156, Symbol: "Dy", Group: "Lantanidos" },
    {index: 157, Symbol: "Ho", Group: "Lantanidos" },
    {index: 158, Symbol: "Er", Group: "Lantanidos" },
    {index: 159, Symbol: "Tm", Group: "Lantanidos" },
    {index: 160, Symbol: "Yb", Group: "Lantanidos" },
    {index: 161, Symbol: "Lu", Group: "Lantanidos" },

    {index: 162, Symbol: "", Group: "Vacio" },
    {index: 163, Symbol: "", Group: "Vacio" },
    {index: 164, Symbol: "", Group: "Vacio"},
    {index: 165, Symbol: "Ac", Group: "Actinidos" },
    {index: 166, Symbol: "Th", Group: "Actinidos" },
    {index: 167, Symbol: "Pa", Group: "Actinidos" },
    {index: 168, Symbol: "U", Group: "Actinidos"},
    {index: 169, Symbol: "Np", Group: "Actinidos" },
    {index: 170, Symbol: "Pu", Group: "Actinidos"},
    {index: 171, Symbol: "Am", Group: "Actinidos" },
    {index: 172, Symbol: "Cm", Group: "Actinidos" },
    {index: 173, Symbol: "Bk", Group: "Actinidos" },
    {index: 174, Symbol: "Cf", Group: "Actinidos" },
    {index: 175, Symbol: "Es", Group: "Actinidos" },
    {index: 176, Symbol: "Fm", Group: "Actinidos" },
    {index: 177, Symbol: "Md", Group: "Actinidos" },
    {index: 178, Symbol: "No", Group: "Actinidos" },
    {index: 179, Symbol: "Lr", Group: "Actinidos" }
];

    

router.get("/", function(req,res,next){
    res.render("home", {layout: false, elementosTabla: elementosTabla});
});

module.exports = router;